[package]
name = "cpitranstoken"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.1.9"
spl-token = { version = "7.0.0", features = [ "no-entrypoint" ] }

[dev-dependencies]
solana-program-test = "2.1.9"
solana-sdk = "2.1.9"

[lib]
crate-type = ["cdylib", "lib"]